### ISSUE TITLE
Getting first project as a Freelance

### ISSUE THREAD

**Issue by Vaibhavpratapsingh22** [Vaibhavpratapsingh22/Courses#111]
# Freelance
A freelancer is a self-employed person who offers services, often working on several jobs for multiple clients at one time. ... Freelancers usually earn money on a per-job basis, charging hourly or daily rates for their work. Freelance work is usually short-term.
### Chapter 1 - Setting up profile
    1. What is must in profile
    2. How to organize profile
    3. Tips for setting up a perfect profile
### Chapter 2 - Making strategy
    1. Things to keep in mind
    2. What should be in your hand before bidding
### Chapter 3 - Selecting Clients
    1. Who is your client
 ### Chapter 4 - Bidding for projects
    1.  How to bid on projects
    2. Proposal templates 
    3. Tips for bidding
  
### Root Directory Structure
C-12-freelance
- [x] 1- profile
- [x] 2- strategy
- [x] 3- clients
- [x] 4- bidding
- [x] README.md

### Challenge
- [x] Get 2 projects in one month. 

### PR Review Guidelines
1. Branch is named properly (all small-letters, format '`freelance-`'). for eg., the branch name for chapter 1 would be `freelance-profile`
2. MD File is named according to the given format
3. The document is formatted consistently
4. Content is given in an easy-to-understand language
5. There are no English errors
6. File has at most 50 lines
7. PR is linked to this issue

### PR Reviewers
@udeysingh95
@giteshk11

**Comment by udeysingh95** [comment]
How about skills? presenting skills? finding the right project? calculating the right amount to bid and then comes the bidding part? 
Lets try to have some more refined intermediate steps here. 
@giteshk11 what else is involved in landing such a project
