### ISSUE TITLE
greedy-algorithm

### ISSUE THREAD

**Issue by udeysingh95** [Vaibhavpratapsingh22/Courses#13]
This would be added to the algorithm folder. branch name "algorithm-greedy". This issue will be implemented for learning purposes. 
The reviewer would be added at some later point. 
The aim is just to get hands-on these dynamic algorithms.

**Comment by Vaibhavpratapsingh22** [comment]
Yeah @udeysingh95 absolutely true. In this branch i.e "algorithm-greedy" we will discuss about how to find the shortest  paths
using MST(minimum spanning tree). In this there will be 3 methods or 3 greedy methods as follow:
1. Kruskal's method
2. Prim's method
3. Dijkstra method(single source path)
