### ISSUE TITLE
Naming .md files

### ISSUE THREAD

**Issue by Vaibhavpratapsingh22** [Vaibhavpratapsingh22/Courses#14]
So @udeysingh95  as u told that .md files should only be pushed with the README.md and that's true but what i was thinking is that to add links in the initial README file. This lead me to an idea to change the files name in order to generate links.
So i think i have to change the idea..

**Comment by udeysingh95** [comment]
Yeah - I saw where you were headed. and for that, you changed the first README file to INDEX - which resulted in no README file in the root which means no already rendered documentation for the repo. 
and then you renamed the internal README's to 1 and 2 - which had a similar effect. 
.md files should only be pushed with README.md - no no - this is not the correct understanding. README.md files are generally pushed with every new folder you create. And it also keeps getting regular updates as files are changed in that folder.

**Comment by Vaibhavpratapsingh22** [comment]
Understood your point @udeysingh95
