### ISSUE TITLE
Understanding Rebase Feature

### ISSUE THREAD

**Issue by Vaibhavpratapsingh22** [Vaibhavpratapsingh22/Courses#16]
Today i rebased a branch named "algorithm-search" with the "datastructure" branch . I am generating a PR so @udeysingh95  U can either give a green signal or u can dismiss this . This will make me clear that the step i had taken was right or wrong .

**Comment by udeysingh95** [comment]
You tried to rebase on a branch which is already merged in the master. so you actually based algorithm-search on master itself and not on datastructure. Rebase actually is helpful when a branch has some different state as of master and you want to take those changes and work on them in 2nd new branch. For that, the base branch should be alive and away from master. And the preposition used for rebasing is - "ON" not with. So if you say that "I have rebased algorithm-search on datastructure" - the branch structure will looking like - 
### master -> datastructure -> algorithm-search
## Here is a small lecture on good rebasing and further terminologies of Github. you can check it now - you are on a good point to learn this. 

- [ ] Go through: https://www.youtube.com/watch?v=2sjqTHE0zok&list=WL&index=2&t=1330s
