### ISSUE TITLE
Software Engineering Course

### ISSUE THREAD

**Issue by udeysingh95** [Vaibhavpratapsingh22/Courses#22]
# Software Engineering
Software engineering pertains to building and developing intangible products for today's modern world. We routinely use software to accomplish everyday tasks like online banking, messaging friends, storing files in the cloud, and so much more which an engineer built.

You will gain not only knowledge and practical experience of the latest technologies, but also a grounding in the underlying principles of the subject. It is this combination of skills that will us to keep pace with this fast-evolving subject! 

### Chapter 1 - Introduction
1. Definition of Software
    - Program versus Software
    - Software Crisis
2. Software Characteristics
3. Definition of Software Engineering
4. Elements of Software Engineering

### Chapter 2 - Software Development Process Models
1. Introduction
2. Phases in Software Development
    - Requirement Gathering 
    - Requirement Analysis
    - Software Design 
    - Software Development
    - Software Testing
    - Delivery
    - Feedback
    - Maintenance
3. The Waterfall Model
    - Introduction
    - Advantages
    - Applications
    - Limitations/ Disadvantages

### Chapter 3 - Agile Methods
1. Introduction
    - What is Agile? 
    - Why Agile? 
    - VUCA world
    - Advantages
    - Applications areas
    - Phases in Agile Software Development
2. Lightweight Agile Frameworks 
    - Kanban
    - Scrum
    - XP 
    - LeSS
3. Scaled Agile Frameworks 
    - LeSS HUGE
    - SAFe

### Chapter 4 - Software Project Planning
1. Definition of Project
    - Project versus Product
2. Definition of Project Planning
3. Cost-Estimation
4. Resource Allocation
5. Risk Management
6. Project Scheduling
    - Gantt Charts
7. Capability Maturity Model (CMM) 
    -  Levels of CMM
    - Applications

### Chapter 5 - Software Designing
1. Objective of Software Designing
2. Object-oriented Concepts
3. UML
    - Goals of UML
    - Opensource UML tools
    - Things
    - Relationships
    - Diagrams
4. Types of UML Diagrams
    - Class Diagram
    - Component Diagram
    - Use Case Diagram
    - Activity Diagram
    - Sequence Diagram

### Chapter 6 - Software Testing
1. Introduction
2. Testing Strategies
    - Unit testing
    - Integration testing
    - System testing
    - Validation testing

### Root Directory Structure
4-software-engineering
- [x]   1-introduction.md
- [x]   2-development-models.md
- [x]   3-development-models-agile.md
- [x]   4-project-planning.md
- [x]    5-software-design.md
- [x]    6-testing.md
- [x]    7-challenge-se-class-diagram.md
- [x]    8-challenge-se-component-diagram.md
- [x]    README.md

### README file
This will contain an overview of each file in this folder. This would be updated with each new file added. 

### 5-software-design.md
**Challenge**
- [x] x-challenge-se-class-diagram.md
- [x] x-challenge-se-component-diagram.md

### 6-testing.md
Do not put lot of effort in this file because one of our course is **Quality Assurance** and we will talk deeply on this topic in that course. 

### PR review guidelines
1. Branch is named properly (all **small-letters**, format 'se-'<file-name>). for eg. branch name for chapter 4 would be 'se-development-models-agile'
2. MD File is named according to the given format
3. Document is formatted consistently
4. Content is given in an easy-to-understand language
5. There are no English errors 
6. File has at most 200 lines or 2500 characters
7. PR is linked to this issue
8. Reviewed by at least two reviewers

### PR reviewers
1. @giteshk11 
2. @Manish-pal 
3. @udeysingh95

**Comment by udeysingh95** [comment]
Chapter 2 is in ready state as well. Once you think you have time to start with it. you can create a branch and start working on it.

**Comment by udeysingh95** [comment]
Chapter 3 is in the ready state as well.

**Comment by udeysingh95** [comment]
Chapter 4 is in the ready state as well.

**Comment by Vaibhavpratapsingh22** [comment]
> Chapter 4 is in the ready state as well.
In this chapter Lightweight Agile Frameworks and Scaled Agile Frameworks are to be discussed in deep or only definition and a flow chart ?

**Comment by udeysingh95** [comment]
### Chapter 5 
Needs some content, sub-topics - any suggestions there?
@giteshk11 @siddharth2848 @Dhillon-in ?

**Comment by udeysingh95** [comment]
@Vaibhavpratapsingh22 are you clear about the chapter 4 now? 
file name: `4-project-planning.md`
content is also given in there. Reach me in wapp group if any further info is needed on this

**Comment by udeysingh95** [comment]
Also, I am seeing lately that you are working on local machine and then pushing the whole thing at once. 
This is not why we started to work with git in first place. I would recommend you to create branch always and then start creating content on it. 
It is ok - that we come across several merge conflicts - but we need ot face them and learn how to deal with them. 
Creating whole thing outside and then pushing a lot of stuff - is ok for now - but when you start working on projects - sometimes code on master changes drastically that whatever you were using as base in your local system - makes no sense. 
@Vaibhavpratapsingh22
