### ISSUE TITLE
DBMS

### ISSUE THREAD

**Issue by udeysingh95** [Vaibhavpratapsingh22/Courses#24]
# DBMS
**Database** is a collection of inter-related data which helps in efficient retrieval, insertion and deletion of data from database and organizes the data in the form of tables, views, schemas, reports etc.
A **database management system** refers to the technology for creating and managing databases. DBMS is a software tool to organize (create, retrieve, update, and manage) data in a database. The main aim of a DBMS is to supply a way to store up and retrieve database information that is both convenient and efficient.

### Chapter 1 - Introduction
    1. Databases and types 
    2. Importance and Applications
    3. DBMS
    4. Types of DBMS
    5. Advantages
### Chapter 2 - Data Modeling
    1. Relation data model (relational algebra) 
    2. Semantic Modeling 
        - Using entity Concepts and Terminology and UML
        - Logical data modelling using the Relational Model 
    3. ER Model 
        - Terminologies
        - Relations
        - Mapping
        - Graphical representation
    4. Enhanced ER Model
        - Specialization
        - Aggregation
        - Composition
### Chapter 3 - SQL
    1. Overview
### Chapter 4 - Database Architecture
    1. Design Phases 
        - Conceptual Design
        - Logical Design
        - Physical Design
    2. Database Storages
    3. Database Backup
    4. Database Transaction Handling
        - ACID Properties
        - Deadlock
        - Concurrent modifications
### Chapter 5 - RDBMS
    1. Terminology
    2. Normalization
    3. Joins
    4. Advance Database Applications
    5. Limitations of RDBMS
### Chapter 6 - Extensions of DBMS
    1. SQL as programming Language
        - SQL/PSM
        - PL/SQL
    2. Control Statements
    3. Exceptions
    4. Cursors
    5. Stored Procedures
    6. Functions
    7. Recursive Queries
    8. Triggers
    9. SQL Injection 
### Chapter 7 - ORDBMS
    1. Overview
    2. Row & Reference types
    3. User-defined types
    4. Supertype / Subtype relationships
    5. User-defined procedures, functions, and methods
    6. Table Inheritance
    7. Collection Types
    8. Large objects
### Chapter 8 - Advanced Management of Data
    1. Distributed Databases
        - Overview
        - DDBMS
        - Heterogenenous DDBMS
        - Homogeneous DDBMS
        - Scalability
        - Network Partitioning
        - Partition Tolerance
        - Data Fragmentation
    2. Advantages of DDBMS
    3. NoSQL Databases
        - Structured Data 
        - Semi-structured Data 
        - CAP Theorem
        - NoSQL characteristics
    4. Types of NoSQL Systems
        - Document Stores 
        - Key-value Stores
        - Wide Column Stores
        - Graph-Databases
        - Hybrid Systems
### Chapter 9 - MongoDB
    1. Overview 
    2. MongoDB Data Model
    3. Creating Collections
    4. CRUD Operation
    5. Sharding
    6. Replication 

### Root Directory Structure
5-dbms
- [x] 1-introduction.md
- [x] 2-data-modeling.md
- [x] 3-sql-overview.md
- [x] 4-database-architecture.md
- [x] 5-rdbms.md
- [ ] 6-extensions-dbms
- [x] 7-ordbms.md
- [x] 8-advanced-management.mdmd
- [ ] 9-mongodb
- [ ] README.md

### README 
This will contain an overview of each file in this folder. This would be updated with each new file added.

### Chapter 6 Directory Structure
 6-extensions-dbms  
- [ ] 1-database-structure.md
- [ ] 2-control-statements.md
- [ ] 3-exceptions.md
- [ ] 4-cursors.md
- [ ] 5-stored-procedures.md
- [ ] 6-functions.md
- [ ] 7-recursive-queries.md
- [ ] 8-triggers.md
- [ ] 9-sql-injection.md
- [ ] README.md

### Chapter 9 Directory Structure
 9-mongodb
- [x] 1-get-started.md
- [x] 2-data-model.md
- [x] 3-collections.md
- [x] 4-crud-operation.md
- [x] 5-sharding.md
- [ ] 6-replication.md 

**README** here will contain only an overview to PL/SQL and then all the points in this directory. All the points could be just state there without any description or could be quickly explained as well using images or short paragraphs. 
**Branching** could be named as `dbms-extensions-database-structure` or `dbms-extensions-functions`

### Challenge
- [ ] **Chapter 6** is PL/SQL hands-on work. It will take time but it is not the end of the world level difficult. Add the commands and screenshots from your use case only. For help, reach out to us. 
- [ ] **Chapter 9** is MongoDB implementation on your system. Add screenshots and commands from your local system and use only. No images shall be taken from the internet for this chapter. Our Github team has good hands-on experience in working with MongoDB, so feel free to reach out to us in case of problems or lost. @giteshk11 is an expert here. 

### PR Review Guidelines
1. Branch is named properly (all small-letters, format 'dbms-'). for eg., branch name for chapter 5 would be 'dbms-rdbms'
2. MD File is named according to the given format
3. The document is formatted consistently
4. Content is given in an easy-to-understand language
5. There are no English errors
6. File has at most 250 lines
7. File has at most 15 visualizations (images+tables)
8. PR is linked to this issue
9. Reviewed by at least two reviewers

### PR Reviewers
@siddharth2848 
@udeysingh95 
@giteshk11

**Comment by udeysingh95** [comment]
@siddharth2848 @giteshk11 could you support me here with the course outline design.
Maybe by writing the first draft of the course outline here. Then we can refine it together. What do you say?
I would really appreciate your expert input here.
and what is your opinion about - shall we go for Modern DBs as well or keep it straight forward and simple?

**Comment by udeysingh95** [comment]
[AMD Notes_.pdf](https://github.com/Vaibhavpratapsingh22/Courses/files/5029174/AMD.Notes_.pdf)
A sample course outline could be fetched from this file. 
i am looking for a better outline still.

**Comment by udeysingh95** [comment]
## Basics
- what are Databases
- why do we use them
- DBMS
- Importance of Database
- Advantages of DBMS
- Disadv

- RDBMS
- Semantic Modeling
    - using entity Concepts and Terminology and UML
    - Logical data modeling using the Relational Model

## Med Level or Req for Advanced Topics
- Relational data model and languages (relational algebra, SQL)
- Normalization
- Query Processing
- Physical data modeling and Indexing

- Conceptual Desing
- Logical Design
- Physical Design

- The enhanced ER model

- Standard and Advanced DB applications
- Weakness of RDBMS

##Advanced Topics: 
- Object-Relational DB concepts
- Extension of SQL
- PL/SQL (only theory)
- Distributed DB Concepts
- NoSQL and Big Data Storage Systems

**Comment by giteshk11** [comment]
The topics you mentioned above are good enough acc. to me

**Comment by siddharth2848** [comment]
What is DBMS?
**Database** is a collection of inter-related data which helps in efficient retrieval, insertion and deletion of data from database and organizes the data in the form of tables, views, schemas, reports etc.
A **database management system** refers to the technology for creating and managing databases. DBMS is a software tool to organize (create, retrieve, update, and manage) data in a database. The main aim of a DBMS is to supply a way to store up and retrieve database information that is both convenient and efficient.

**Comment by udeysingh95** [comment]
[AMD - Lecture 07.pdf](https://github.com/Vaibhavpratapsingh22/Courses/files/5044921/AMD.-.Lecture.07.pdf)
[AMD - Lecture 08.pdf](https://github.com/Vaibhavpratapsingh22/Courses/files/5044922/AMD.-.Lecture.08.pdf)
[AMD - Lecture 09.pdf](https://github.com/Vaibhavpratapsingh22/Courses/files/5044923/AMD.-.Lecture.09.pdf)
[Uploading AMD - Lecture 10.pdf…]

Here are some reference files for you to have help in chapter 7 and chapter 8. 
These are some lecture Slides from Advanced Management of Data course in TUC Master Program.

**Comment by udeysingh95** [comment]
[AMD - Lecture 01.pdf](https://github.com/Vaibhavpratapsingh22/Courses/files/5062761/AMD.-.Lecture.01.pdf)
Semantic modelling is basically modelling design for database. 
What would be the elements, relations, keys in it. These are the semantics of a database. and Semantic Modeling means to create a model to accommodate all the semantics in a database - meeting all the requirements. 
it could be achieved using ER model or Enhanced ER model - these are the ways to do semantic modelling. 
Check from slide no. 26 onwards in the attachment.

**Comment by Vaibhavpratapsingh22** [comment]
@siddharth2848 @udeysingh95  can u tell me some subtopics of database storages in chapter- 4.  What I found is data storages are of two types:
1. Row-oriented storage
2. Column-oriented storage

Is this correct??

**Comment by udeysingh95** [comment]
It includes backups and types of memories used in backups - types of backups and all as well. RAID and stuff also falls in this only.

**Comment by Vaibhavpratapsingh22** [comment]
> It includes backups and types of memories used in backups - types of backups and all as well. RAID and stuff also falls in this only.

I think u misunderstood you have told about data backup, but I wanted to know about data storage. Plz check it once 👍

**Comment by Vaibhavpratapsingh22** [comment]
@siddharth2848 @udeysingh95, can u tell me something about Concurrent modifications which comes under Database Transaction Handling in chapter-4.

**Comment by udeysingh95** [comment]
When multiple transactions can happen on single data source. 
here is a link for further info: https://infocenter.informationbuilders.com/wf80/index.jsp?topic=%2Fpubdocs%2Fmaintain%2FMaintainDevelopingApps%2Fsource%2Ftopic187.htm

**Comment by udeysingh95** [comment]
### Chapter 6
As our DB is deployed, I think it would be a good idea to talk about the deployment quickly in README file. Also, for the readers and reviewers - it would be helpful to have an understanding of where and how it was hosted. 
What do you say? @Vaibhavpratapsingh22

**Comment by udeysingh95** [comment]
@Vaibhavpratapsingh22 anything moving here?

**Comment by Vaibhavpratapsingh22** [comment]
> @Vaibhavpratapsingh22 anything moving here?

Yes @udeysingh95 i have started with chapter 7 which is ORDBMS. Branch is also published, will file a PR in one or two days.
