### ISSUE TITLE
Linkedin Profile

### ISSUE THREAD

**Issue by udeysingh95** [Vaibhavpratapsingh22/Courses#33]
# Linkedin
The introduction comes here...
we will learn how to make a great all-star Linkedin profile here and also set one for ourselves. 
for all those, who already have Linkedin profiles - can review theirs and help others to make a great one

### Chapter 1 - Linkedin Profile
    0. Url
    1. Picture and Cover
    2. Headline
    3. Summary
    4. Experience
    5. Education 
    6. Skills and Endorsements
    7. Accomplishments
    8. Interests
    9. Featured
### Chapter 2 - Networking
    1. why
    2. how
    3. tips
### Chapter 3 - Recommendation
    1. Importance 
    2. Recommending Tips
    3. Request Template
### Chapter 4 - Posting
    1. Content Tips
    2. Timings
    3. Engagement on Posts
    4. Commenting
### Chapter 5 - Articles
    1. why
    2. Content Tips
    3. Article Template
    4. Timings
    5. Engagement
    6. Tips
### Chapter 6 - How to Optimize Your Profile for Better Search Visibility
    1. What are keywords?
    2. What can keywords do?
    3. How should I use keywords?
    4. What are the best keywords?

### Root Directory Structure
11-linkedin
- [x] 1-profile.md
- [x] 2-networking.md
- [x] 3-recommendation.md
- [x] 4-posting.md
- [x] 5-articles.md
- [x] 6-optimize.md
- [x] README.md

### README.md
    1. Linkedin Overview
    2. Learning Objectives
    3. Personal Branding
    4. Engagement

### Challenge
- [x] Create an ALL STAR Linkedin Profile.
- [x] Get it reviewed from at least from 2 experts other than Team Github.
- [x] Reach 500+ connections within a month.
- [x] Get at least 1 recommendation from Uni Professor or someone equivalent.

### PR Review Guidelines
1. Branch is named properly (all small-letters, format '`linkedin-`'). for eg., the branch name for chapter 4 would be `linkedin-posting`
2. MD File is named according to the given format
3. The document is formatted consistently
4. Content is given in an easy-to-understand language
5. There are no English errors
6. File has at most 100 lines
7. PR is linked to this issue

### PR Reviewers
@Dhillon-in 
@siddharth2848 
@Manish-pal 
@udeysingh95
@giteshk11

**Comment by Dhillon-in** [comment]
Try to incorporate the following things :
The Linkedin Profile of a candidate should incorporate the following
1. Headline - The profile headline should be clear and concise it should incorporate the types of job roles the candidate is looking for and also background like a certain educational qualification.Also the different roles can be separated using '|'
eg-> Former Product @Adobe ||  Looking for product management opportunities 
2. Links to personal website or git repository 
3. All internship descriptions highlighting the roles and performance metrics
4. Formal email address
5. Volunteer experience with responsibilities wherever applicable 
6. Highlighting skills also try to give the skill quiz by linkedin 
7. Projects with detail about the scope of the project and what was achieved 
8. Detailed about section 
9. Tone should be consistent throughout the profile

**Comment by Dhillon-in** [comment]
https://www.linkedin.com/learning/rock-your-linkedin-profile/see-your-profile-as-your-story

Check this out its free so we can take out ideas from here as well .

**Comment by udeysingh95** [comment]
Thanks for your input. We could consider all those points in 
### Linkedin Profile Tips

Other parts that I was thinking of was 
- what is LinkedIn?
- Why LinkedIn?
- Build your Linkedin Profile (sub-topics given in your comment)
- Personal Branding on Linkedin
- Linkedin Engagement
    - Posting
    - Articles 
    - Commenting
