### ISSUE TITLE
Scrum Master Role

### ISSUE THREAD

**Issue by udeysingh95** [Vaibhavpratapsingh22/Courses#42]
# Scrum Master 
This course will help you in learning how to use Scrum to optimize value, productivity, and the total cost of ownership of software products. Tools are provided to enable all of you to relate to behavioral shifts, work with people and teams, coach and facilitate techniques, and address the organization. We will learn about the role and various skills here.

### Chapter 1 - Scrum
    1. Scrum Framework
         - Scrum Principles 
         - Scrum Values
    2. Scrum Team
    3. Scrum Events
### Chapter 2 - Scrum Master
    1. Who is a Scrum Master?
    2. Roles a Scrum Master
    3. Responsibilities of a Scrum Master
    4. Scrum Master Focus Areas
    5. Scrum Master performance metrics
### Chapter 3 - Facilitation
    1. Who is a Facilitator?
    2 Why do we need a Facilitator?
    3. The how: the flow of a facilitated event
    4. The who: high-quality facilitator 
    5. Science of Facilitation
### Chapter 4 - Team-building 
    1. What Is Team Building?
    2. How Does Team Building Work?
    3. Kick-off Agile Team
    4. Team building activities
    5. Making High performing Team
    6. 5 Dysfunctions of a Team model
    7. Tuckman's model of team development
### Chapter 5 - Moderation
    1. What is an (event) moderator?
    2. How To Be a Great Moderator
    3. Characteristics of a great moderator?
### Chapter 6 - Teaching
    1. What is a teacher?
    2. Scrum Master as a Teacher
    3. Scrum Master topics
    4. Teaching Frameworks 
### Chapter 7 - Coaching
    1. What is coaching?
    2. What coaching is not
    3. Who does the Scrum Master coach?
    4. How to do coaching?
    5. Active Listening model
    6. Powerful questions
    7. Art of asking Powerful questions?
### Chapter 9 - Remote Work
    1. Remote vs co-located
    2. Remote Work Challenges 
    3. Tips for remote work
    4. Remote Retro Games   
### Chapter 10 - Remote Toolkit
     1. JIRA
     2. Trello
     3. Whiteboards
             - MIRO
             - MURAL
             - Jamboard
     4. Github
     5. Funretro.io      

### Root Directory Structure
7-scrum-master-role
- [x] 1-scrum.md
- [x] 2-scrum-master.md
- [x] 3-facilitation.md
- [x] 4-team-building.md
- [x] 5-moderation.md
- [x] 6-teaching.md
- [x] 7-coaching.md
- [x] 8-anti-patterns.md
- [x] 9-remote-work.md
- [x] 10-remote-toolkit.md
- [x] README.md

### README.md
    1. Agile Overview
    2. Scrum 
    3. Scrum Master Role

### Challenge
- [x] Agile Estimation Workshop
- [x] Coaching PO on good User Stories writing 
- [x] Running Team Vision Workshop with Scrum Team 

### PR Review Guidelines
1. Branch is named properly (all small-letters, format '`sm-`'). for eg., branch name for chapter 3 would be `sm-facilitation`
2. MD File is named according to the given format
3. The document is formatted consistently
4. Content is given in an easy-to-understand language
5. There are no English errors
6. File has at most 100 lines
7. PR is linked to this issue

### PR Reviewers
@udeysingh95

**Comment by udeysingh95** [comment]
Prioritize the chapters again in the following order: 
1. Scrum
2. Scrum Master 
3. Facilitation
4. Team-building

Rest can stay the same. 
- [ ] Add sub-topics to all the chapter names.

**Comment by SaarthakDeshmukh** [comment]
Okay, As soon as @Vaibhavpratapsingh22 adds me to the repo, I will start making changes. @udeysingh95

**Comment by udeysingh95** [comment]
Chapter 6 & 7 needs sub-topics. 
Chapter 8 could be removed for now. 
Rest looks good.

**Comment by udeysingh95** [comment]
# Good to go. 
Start pushing work on this now.

**Comment by udeysingh95** [comment]
some baby issues out of this big one 
1. 5 Dysfunctions of a Team
2. Tuckman model of team development
3. Liberating Structures
4. Agile Estimation
5. Designing Metrics 
6. LeSS
